"""
================================================================================
Temporal Window Generation (M2, item 3)
================================================================================
Converts a single continuous recording into a list of fixed-length,
non-overlapping (by default) time windows, each of which becomes one
training "sample". A window is associated with whichever ground-truth
boxes have their annotation timestamp inside that window.

DESIGN DECISIONS (documented for the paper):
  - Window length default: 50,000 us (50 ms), matching the temporal-bin
    convention already fixed for voxelization (10 bins configured
    elsewhere) and common event-frame accumulation windows in the
    event-based detection literature.
  - Windows are generated by tiling [t_min, t_max) of the recording in
    fixed steps of `window_us` (stride = window_us by default, i.e. no
    overlap; `stride_us` can be set smaller than `window_us` for
    overlapping windows if desired later).
  - A window with zero associated ground-truth boxes is still a VALID
    sample (background-only window) and is kept by default, since a
    detector must learn "no object" regions too; set
    `drop_empty_windows=True` to exclude them if desired.
  - Window boundaries never depend on box timestamps -- they are computed
    purely from the recording's own duration, so window generation is
    reproducible independent of the annotation file.
================================================================================
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import List

import numpy as np


@dataclass
class TemporalWindow:
    recording_stem: str
    window_index: int
    t_start: int
    t_end: int


def generate_windows_for_recording(
    recording_stem: str,
    t_min: int,
    t_max: int,
    window_us: int = 50_000,
    stride_us: int = None,
) -> List[TemporalWindow]:
    """
    Tiles [t_min, t_max) into windows of length `window_us`, advancing by
    `stride_us` each step (defaults to `window_us`, i.e. non-overlapping).
    The final partial window (shorter than window_us) is dropped, since a
    truncated window would have systematically less event content and would
    bias any density/statistics comparison across windows.
    """
    if window_us <= 0:
        raise ValueError(f"window_us must be positive, got {window_us}")
    stride_us = stride_us or window_us
    if stride_us <= 0:
        raise ValueError(f"stride_us must be positive, got {stride_us}")

    duration = t_max - t_min
    if duration < window_us:
        return []

    windows = []
    idx = 0
    start = t_min
    while start + window_us <= t_max:
        windows.append(TemporalWindow(
            recording_stem=recording_stem,
            window_index=idx,
            t_start=int(start),
            t_end=int(start + window_us),
        ))
        idx += 1
        start += stride_us
    return windows


def assign_boxes_to_window(boxes: np.ndarray, window: TemporalWindow) -> np.ndarray:
    """Returns the subset of `boxes` whose 'ts' falls inside [t_start, t_end)."""
    ts_field = "ts" if "ts" in boxes.dtype.names else "t"
    mask = (boxes[ts_field] >= window.t_start) & (boxes[ts_field] < window.t_end)
    return boxes[mask]
